const fs = require("fs");
const path = require("path");

if (process.argv[2] == null) {
  console.error(
    `Usage: node ${path.basename(process.argv[1])} <input directory>`
  );
  process.exit(1);
}

const inputPath = process.argv[2];
const outputPath = "./celerity-runtime/docs/api";
const baseUrl = "/docs/api";

if (!fs.existsSync(inputPath)) {
  console.error(`Input directory does not exist: ${inputPath}`);
  process.exit(1);
}

/**
 * Write the _category_.json settings file for a subdirectory.
 * Importantly, here we disable collapsing of entries in the sidebar.
 * This is required because we hide all of the entries except for the index file
 * using the custom `sidebar_class_name` that is set in writeMdx.
 */
function writeCategorySettings(subdir) {
  const label = subdir.charAt(0).toUpperCase() + subdir.slice(1);
  const settings = {
    label,
    collapsible: false,
  };
  const json = JSON.stringify(settings, null, 2);
  fs.writeFileSync(path.join(outputPath, subdir, "_category_.json"), json);
}

function writeMdx(subdir, fileName, title) {
  const mdxContent = `\
---
hide_title: true
pagination_next: null
pagination_prev: null
custom_edit_url: null
sidebar_class_name: "${fileName === "index" ? "sidebar-show" : "sidebar-hidden"}"
title: "${title}"
---
import html from "!!raw-loader!./${fileName}.html";

<head>
  <script src="/js/highlight.min.js" />
  <script src="/js/api_docs.js" defer />
</head>

<div dangerouslySetInnerHTML={{ __html: html }} />`;

  fs.writeFile(
    path.join(outputPath, subdir, `${fileName}.mdx`),
    mdxContent,
    (err) => {
      if (err) throw err;
      console.log(`Generated ${subdir}/${fileName}.mdx`);
    }
  );
}

function parseTitle(html) {
  let title = "";
  const match = html.match(/<h1>(.*?)<\/h1>/);
  if (match != null) {
    title = match[1];
  } else {
    // We have to fiddle it out of the breadcrumbs...
    // If that doesn't work, give up.
    const breadcrumbMatch = html.match(/<li class="is-active">(.*?)<\/nav>/);
    if (breadcrumbMatch != null) {
      const spanMatch = breadcrumbMatch[1].match(/<span>(.*?)<\/span>/);
      if (spanMatch != null) {
        title = spanMatch[1];
      }
    }
  }
  // Undo HTML escaping
  title = title.replace(/&gt;/g, ">");
  title = title.replace(/&lt;/g, "<");
  return title;
}

/**
 * The URLs generated by leafy-green-doc are not directly compatible with our setup,
 * so we need to do some post-processing.
 *
 * FIXME: We should have options to do this in leafy-green-doc
 */
function fixUrls(html, allDirs) {
  for (const subdir of allDirs) {
    // Replace all links to category index pages with the category directory
    html = html.replace(
      new RegExp(`${subdir}\/index\.html`, "g"),
      `${subdir}/`
    );
    // Replace all relative "../" links with absolute paths
    html = html.replace(
      new RegExp(`\.\.\/${subdir}/`, "g"),
      `${baseUrl}/${subdir}/`
    );
  }

  // Finally, replace all ".html" extensions with a slash
  html = html.replace(/\.html/g, "/");

  return html;
}

// Since AdaptiveCpp (formerly hipSYCL) aliases the sycl namespace to hipsycl::sycl,
// we have to replace it in the generated HTML files.
// TODO: We should have an option to do this in leafy-green-doc
function replaceSyclNamespace(html) {
  return html.replace(/hipsycl::sycl/g, "sycl");
}

function processSubdir(subdir, allDirs) {
  fs.mkdirSync(path.join(outputPath, subdir), { recursive: true });
  writeCategorySettings(subdir);

  fs.readdir(path.join(inputPath, subdir), (err, files) => {
    if (err) {
      return console.log("Unable to scan directory: " + err);
    }

    files.forEach((file) => {
      if (path.extname(file) !== ".html") return;

      const fileName = path.basename(file, ".html");

      const html = fs.readFileSync(path.join(inputPath, subdir, file), "utf8");
      const title = parseTitle(html);
      const withFixedUrls = fixUrls(html, allDirs);

      const withSyclNamespace = replaceSyclNamespace(withFixedUrls);

      fs.writeFileSync(
        path.join(outputPath, subdir, `${fileName}.html`),
        withSyclNamespace
      );

      writeMdx(subdir, fileName, title);
    });
  });
}

fs.readdir(inputPath, { recursive: true }, (err, files) => {
  if (err) {
    return console.log("Unable to scan directory: " + err);
  }

  allDirs = [];
  files.forEach((file) => {
    if (fs.lstatSync(path.join(inputPath, file)).isDirectory()) {
      allDirs.push(file);
    }
  });
  for (const subdir of allDirs) {
    processSubdir(subdir, allDirs);
  }
});
